name: Build, Test, and Deploy container app to Azure Web App - fakenews

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --deploy --system --ignore-pipfile

    - name: Run tests with pytest
      env:
        PYTHONPATH: /home/runner/work/NLP_Fake_News/NLP_Fake_News
      run: pipenv run pytest -v tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fakenewscon.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2bfe901e4928411e9728ba20b1f777a0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_df6ffac1370c46669f71cb06eb89c18f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fakenewscon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2bfe901e4928411e9728ba20b1f777a0 }}/fakenews:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fakenews'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_223d0cccf1cc4d7f99fdd42494762127 }}
        images: 'fakenewscon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2bfe901e4928411e9728ba20b1f777a0 }}/fakenews:${{ github.sha }}'
